### ISSUE TITLE
Set Default Country

### ISSUE THREAD

**Issue by ssveronis** [Willena/Android_PhoneNumber_Input#2]
Is there a way to set a default country?

**Comment by Willena** [comment]
Hi ! This feature is not yet implemented. If you need it I can add this feature.

**Comment by ssveronis** [comment]
Well I see here:

https://github.com/Willena/Android_PhoneNumber_Input/blob/8404e8bd46b7a94f38d9315264a5d282fa9f1be9/phoneinputview/src/main/res/values/arrays.xml#L3

that you support 241 countries. I think that we could provide a much better user experience if we could help the user and set the country that he is most likely to use. For example my app is only available in Greece, so my users will probably have a phone number from Greece. It will be much easier for them to see their country selected by default.

**Comment by Willena** [comment]
You're right, a lot of countries are supported. I understand the need. 
If correctly implemented, this could give the programmers the ability to provide a default value based on multiple things (using a custom class) such as: 
* The current user locale
* The current phone number of the user
* An arbitrary choice

I have not a lot of time to work on this, but I'll try to produce something soon.

**Comment by sotiris08** [comment]
I see th update coming.

**Comment by Willena** [comment]
Version v1.3 adds a way to define the country based on the code (FR, US, ...) 
The readme has been updated

**Comment by ssveronis** [comment]
I am trying to use v1.3 but I can't because Android Studio can't import.
I am getting the following error:

![image](https://user-images.githubusercontent.com/62189294/103488745-1301d180-4e18-11eb-9b8f-536306a41e16.png)

![image](https://user-images.githubusercontent.com/62189294/103488758-2b71ec00-4e18-11eb-9f59-102f095c0d6b.png)


I imported with:
`maven { url 'https://jitpack.io' }`

and
`implementation 'com.github.Willena:Android_PhoneNumber_Input:1.3'`

v1.0 and v.1.2 work just fine.
