### ISSUE TITLE
setPhoneNumberHintType and setDefaultCountry not found in CountryConfigurator

### ISSUE THREAD

**Issue by darkengine** [Willena/Android_PhoneNumber_Input#7]
Android Studio says "Cannot resolve method 'setPhoneNumberHintType' in 'CountryConfigurator'" with version 1.0.0.

 setPhoneNumberHintType() and setDefaultCountry() not found in CountryConfigurator's source code.

**Comment by darkengine** [comment]
Sorry for that. Just copy the install Gradle code from ReadMe. Did not notice the latest version is 1.3.1. Problem solved after updating to latest version.

**Comment by darkengine** [comment]
"enum HintType" should be public, or we cannot access it outside the package.

**Comment by Willena** [comment]
Should I reopen the issue for that last message ?

**Comment by darkengine** [comment]
Reopen and fix the access issue would be nice. Thanks for your work.
